### PR TITLE
fix(eslint): ignore the entire `/public` directory

### LINKED ISSUE #22: Ignore the entire `public` directory
### System Info

```shell
—
```

### Expected Behavior

Hi! I would like to suggest for the default eslint config to ignore everything in `public`, not just `public/build`. The folder normally contains build artifacts, and those must never be linted because they are generated. 

### Actual Behavior

Only the `public/build` folder is currently ignored in eslint, which raises eslint warnings/errors if I have, say, a JavaScript file in `public`. 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #22 

## Motivation

One should never lint the public directory. It's comprised mostly of generated/static assets that the developer has little control of (or won't benefit from linting, in the first place).

### CODE REVIEW

**Comment by kettanaito** [comment]
@kettanaito what do you think if I list the `*.json` files explicitly in the `ignores`? As I mentioned before, eslint affects some of the JSON files I have, and it tries to lint them as JS, which is quite off.

File: eslint.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ export const config = [
 			'**/.cache/**',
 			'**/node_modules/**',
 			'**/build/**',
-			'**/public/build/**',
+			'**/public/**',
```
Comment (kentcdodds) [inline eslint.js:30]:
```suggestion
			'**/public/**',
			'**/*.json',
```

**Review by kentcdodds — APPROVED** [review]
Yeah, let's ignore json files too

**Comment by kettanaito** [comment]
Cannot wait to update! Thank you so much.

**Comment by kettanaito** [comment]
@kentcdodds looks like your JSON suggestion wasn't merged so it's not in the release. Will open a new PR with this.

**Comment by kettanaito** [comment]
Opened the PR to ignore JSON files: 24
